/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include <stdint.h>
#include "stm32f407xx_gpio_driver.h"

/***********************************************************************
 * 							MACROS  						     	   *
 ************************************************************************/

#define BUTTON_PRESSED  HIGH

/***********************************************************************
 * 							PROTOTYPES						     	   *
 ************************************************************************/

void Led_Init(void);
void Button_Init(void);


/***********************************************************************
 * 								MAIN      							   *
 ************************************************************************/

int main(void)
{
	// Variable Inits
	uint8_t button_state;

	// GPIO Inits
	Led_Init();
	Button_Init();

	// Loop
	for(;;){

		button_state = GPIO_Pin_DigitalRead(GPIOA, GPIO_PIN_NO_0);

		if(button_state == BUTTON_PRESSED)
			// Button pressed -> Led ON
			GPIO_Pin_DigitalWrite(GPIOD, GPIO_PIN_NO_12, HIGH);
		else
			// Button NOT pressed -> Led OFF
			GPIO_Pin_DigitalWrite(GPIOD, GPIO_PIN_NO_12, LOW);

	}

}

/***********************************************************************
 * 								FUNCTIONS  							   *
 ************************************************************************/

void Led_Init(void){

	GPIO_Handle_t PD12_gpio_handle;

	// Initialize PD12 PIN
	PD12_gpio_handle.pGPIOx = GPIOD;
	PD12_gpio_handle.GPIO_PinConfig.Pin_Number            = GPIO_PIN_NO_12;
	PD12_gpio_handle.GPIO_PinConfig.Pin_Mode              = GPIO_PIN_MODE_OUTPUT;
	PD12_gpio_handle.GPIO_PinConfig.Pin_Output_Type       = GPIO_PIN_PUSH_PULL;
	PD12_gpio_handle.GPIO_PinConfig.Pin_Output_Speed      = GPIO_PIN_SPEED_MEDIUM;
	PD12_gpio_handle.GPIO_PinConfig.Pin_Pull_Up_Pull_Down = GPIO_PIN_NO_PU_PD;
	GPIO_Pin_Init(&PD12_gpio_handle);
}

void Button_Init(void){
	GPIO_Handle_t PA0_gpio_handle;

	// Initialize PA0 PIN
	PA0_gpio_handle.pGPIOx = GPIOA;
	PA0_gpio_handle.GPIO_PinConfig.Pin_Number            = GPIO_PIN_NO_0;
	PA0_gpio_handle.GPIO_PinConfig.Pin_Mode              = GPIO_PIN_MODE_INPUT;
	PA0_gpio_handle.GPIO_PinConfig.Pin_Pull_Up_Pull_Down = GPIO_PIN_PULL_DOWN;
	GPIO_Pin_Init(&PA0_gpio_handle);
}
